modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (28 is current forge version)
license="MIT"
[[mods]] 
modId="muchmoremodcompat" #mandatory
version="${file.jarVersion}"
displayName="Much More Mod Compat"
credits="Thanks for using my mod!"
authors="chickenmcjesus"
description='''
 A small mod adding compatability between various mods.
'''
[[dependencies.muchmoremodcompat]] 
    # the modid of the dependency
    modId="forge" 
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true 
    # The version range of the dependency
    versionRange="[32,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.muchmoremodcompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.muchmoremodcompat]]
	modId = "decorative_blocks"
	mandatory = true
	versionRange = "[1.7.2,)"
	ordering = "BEFORE"
	side = "BOTH" 